FROM golang:1.25-bookworm AS builder

RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    libtesseract-dev \
    libleptonica-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o /app/main ./cmd/api/main.go

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    libtesseract5 \
    libleptonica-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /root/

COPY --from=builder /app/main .

RUN addgroup -S appgroup && adduser -S appuser -G appgroup
RUN chown appuser:appgroup main
USER appuser

EXPOSE 3001
CMD ["./main"]

# dont forget to change user